name: Run Plumbing Bot

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Сheckout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg wget unzip fonts-dejavu-core  # Добавили шрифты

    - name: Cache Vosk model
      uses: actions/cache@v3
      with:
        path: vosk-model-small-ru-0.22
        key: ${{ runner.os }}-vosk-model

    - name: Download Vosk model if not cached
      run: |
        if [ ! -d "vosk-model-small-ru-0.22" ]; then
          echo "Vosk model not found in cache. Downloading..."
          wget https://alphacephei.com/vosk/models/vosk-model-small-ru-0.22.zip
          unzip vosk-model-small-ru-0.22.zip
          rm vosk-model-small-ru-0.22.zip
        else
          echo "Vosk model found in cache."
        fi

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install tensorflow-cpu 
        pip install -r requirements.txt

    - name: Initialize Database
      run: python database.py

    - name: Cache SQLite Database
      uses: actions/cache@v3
      with:
        path: bot_database.db
        key: ${{ runner.os }}-sqlite-db
        restore-keys: |
          ${{ runner.os }}-sqlite-db

    - name: Run Telegram Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_ADMIN_IDS: ${{ secrets.TELEGRAM_ADMIN_IDS }}
      run: |
        python main.py